### ISSUE TITLE
&<modifierClass> will count as a deeper nesting level

### ISSUE THREAD

**Issue by andreechristian** [AtomLinter/linter-scss-lint#188]
Hello,

I am using scss lint in Atom, and i specify the rules of nesting depth should be no greater than 3. I have an edge case where i need to specify something like this

```
.banner {
  <some rules>

  &-navigation {
    <some rules>

    a {
       color: $c-red;

       &.is-active {
         color: $c-green;
       }
    }
  }
}
```

i believe that the output should be equal to

```
.banner {
  <some rules>
}

.banner-navigation {
  <some rules>
}

.banner-navigation a {
  color: #f00;
}

.banner-navigation a.is-active{
  color: #0f0;
}
```

which shouldn't break nesting depth rules that i specified.
yet i get this warning `Nesting should be no greater than 3, but was 4` at `&.is-active {` line

is it a bug that scss lint count `&` as a deeper level?

**Comment by abea** [comment]
It sounds like you're thinking of `SelectorDepth` rather than `NestingDepth`. With SelectorDepth set to three, you'll see no warnings for that with your code. NestingDepth is, as I understand, specifically directed to help us avoid nesting our Sass _rules_ too deeply (as opposed to selectors). As the docs note, "Overly nested rules will result in over-qualified CSS that could prove hard to maintain, output unnecessary selectors and is generally considered bad practice." Even if they're not over qualified, they can get harder to maintain.

That said, if you want to avoid writing selectors deeper than three levels (which you haven't done here), but you're alright with nesting deeper, you can set the [NestingDepth](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#nestingdepth) option differently.

Note: This also might be more of a question for the [scss-lint project](https://github.com/brigade/scss-lint/) than the Atom linter.
