### ISSUE TITLE
Rule name in popup is illegible in light themes

### ISSUE THREAD

**Issue by albell** [AtomLinter/linter-scss-lint#189]
![shorthand-screenshot](https://cloud.githubusercontent.com/assets/1142025/18064972/badfdd8c-6de6-11e6-8bd2-b5129497cc5c.png)

See <a href="https://github.com/steelbrain/linter/issues/1216#issuecomment-238306069">this thread</a>

Apparently once <a href="https://github.com/steelbrain/linter-ui-default">linter-ui-default</a> becomes the UI, then the name of the linter will no longer be themed. So that takes care of the linter name. But not the rule name.

**Comment by Arcanemagus** [comment]
As the trend seems to be moving away from the nice visual cues from the "button style", mainly because different themes are terrible and can't be relied on to provide usable colors... how would you want to see that information exposed?

This is what it currently looks like with the upcoming `linter` and `linter-ui-default` on the theme I use (Seti):
![image](https://cloud.githubusercontent.com/assets/427137/18067141/54b7c272-6df0-11e6-8fb2-79010cbcbb0f.png)

Should the rule name be changed to `[ColorKeyword]`?
![image](https://cloud.githubusercontent.com/assets/427137/18067358/49f71c74-6df1-11e6-9144-7f5f59948ded.png)

Or some other punctuation around it?

**Comment by albell** [comment]
I think I personally prefer the 'button' style. It's a bit faster to visually scan. It's a good structure. If it's the themes that are broken, let's just file tickets on them? Any tips on this appreciated, I'm new to Atom.

**Comment by Arcanemagus** [comment]
The other option is to just force a specific color choice and ignore the user themes.

**Comment by albell** [comment]
Is there a way to have it both ways? A linter default that guarantees basic contrast and legibility, but still with a class hook that themes can use to override?

Or maybe linter-ui-default should also fix the styling of the rule name? Not sure, I just want it to work...

**Comment by Arcanemagus** [comment]
Linter v2 (and thus linter-ui-default) actually completely removes HTML styling from messages, you have pure text or Markdown so I'd like to move away from the bubble style as soon it won't be possible to use anyway.

**Comment by Arcanemagus** [comment]
The rule name is now embedded in the start of the message as `ruleName: Message`.
