### ISSUE TITLE
Error running scss-lint Error: Failed to spawn command `scss-lint`.

### ISSUE THREAD

**Issue by 529570233** [AtomLinter/linter-scss-lint#219]

**Comment by Arcanemagus** [comment]
Do you have [`scss-lint`](https://github.com/brigade/scss-lint) installed and available on your `$PATH`?

**Comment by 529570233** [comment]
I did not change the installation path, which is the plug-in directly installed in Atom.

**Comment by Arcanemagus** [comment]
`scss-lint` is a Ruby 💎 that you need to install on your system, it's not something that is bundled with this package.

**Comment by shudson250** [comment]
So.... a to lint my .scss file I have to install Ruby? What has this world become.

**Comment by Arcanemagus** [comment]
@shudson250 Since `scss-lint` is written in Ruby, yes you have to have Ruby installed to use it.

If you are just looking to lint your SCSS files, I'd recommend following the advice of the `scss-lint` authors and [not using `scss-lint`](https://github.com/brigade/scss-lint#notice-consider-other-tools-before-adopting-scss-lint) 😆.

Both of their recommended alternatives are written in JavaScript, and you can find Atom packages for them at [linter-stylelint](https://atom.io/packages/linter-stylelint), [linter-sass-lint](https://atom.io/packages/linter-sass-lint).

Since I haven't gotten a response from @529570233 I'm going to close this issue, feel free to continue the discussion if you still need help!
